### ISSUE TITLE
action.meta.promise.resolve is not a function

### ISSUE THREAD

**Issue by Thembelani** [adobe/redux-saga-promise#1]
Hi. I'm getting this error when attempting to resolve from a saga.

My code 
`export function * loginUser2(action) {
  // const { seconds, value } = action.payload
  yield delay(1000)
  yield call(resolvePromiseAction, action, 'somevalue')
}`

<img width="499" alt="Screenshot 2020-03-06 at 17 38 00" src="https://user-images.githubusercontent.com/6085377/76097964-4a71d880-5fd1-11ea-80a6-dc064b20b77a.png">

**Comment by ronen** [comment]
Hi.  

That looks like `promiseMiddleware` isn't running.   The middleware is responsible for defining `action.meta.promise.resolve`. 

Did you include the middleware as per the [instructions in the README](https://github.com/adobe/redux-saga-promise#including-the-middleware), making sure that it comes before the redux-saga middleware so that the promise functions will be available to the sagas?

**Comment by Thembelani** [comment]
Oh! .... Fixed. Thank you

**Comment by ronen** [comment]
Glad it's working for you.   I realized that the README could have been clearer so have updated it.  

I also realized that the code could easily throw a clear error message if the middleware is missing; I've made a new release [v1.1.0](https://github.com/adobe/redux-saga-promise/releases/v1.1.0) that does that.  Too late to help you, but maybe will simplify things for somebody else.
